#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=3:00:00
#PBS -l vmem=16gb
#PBS -N peaks
#PBS -V

t1=`jq -r '.t1' config.json`
csd_type=`jq -r '.csd' config.json`
brain_mask=`jq -r '.mask' config.json`

mkdir -p output
ln -sf $t1 ./T1w_acpc_dc_restore_brain.nii.gz
ln -sf $(jq -r .dwi config.json) ./dwi.nii.gz
ln -sf $(jq -r .bvals config.json) ./dwi.bvals
ln -sf $(jq -r .bvecs config.json) ./dwi.bvecs

singularity exec -e docker:/giuliaberto/extract-peaks:1.1 python compute_peaks.py \
                    -t1 $t1 -dwi dwi.nii.gz -bvals dwi.bvals -bvecs dwi.bvecs \
                    -csd_type $csd_type -brain_mask $brain_mask -out_dir .

cp peaks.nii.gz output/peaks.nii.gz
