#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=01:00:00
#PBS -l vmem=16gb
#PBS -N peaks
#PBS -V

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

module unload mrtrix/0.2.12 
module load mrtrix/3.0
module load fsl/5.0.11

t1=`jq -r '.t1' config.json`
csd_type=`jq -r '.csd' config.json`
brain_mask=`jq -r '.mask' config.json`

mkdir -p output
ln -sf $t1 ./T1w_acpc_dc_restore_brain.nii.gz
ln -sf $(jq -r .dwi config.json) ./dwi.nii.gz
ln -sf $(jq -r .bvals config.json) ./dwi.bvals
ln -sf $(jq -r .bvecs config.json) ./dwi.bvecs

python compute_peaks.py -t1 $t1 -dwi dwi.nii.gz -bvals dwi.bvals -bvecs dwi.bvecs -csd_type $csd_type -brain_mask $brain_mask -out_dir .

cp peaks.nii.gz output/peaks.nii.gz
